sudo: false
language: node_js
node_js:
  - '8'
env:
  - EXTENSION_ID=mmcgnaachjapbbchcpjihhgjhpfcnoan
deploy:
  - provider: script
    skip_cleanup: true
    #script: npm run release
    script: npm run build
    on:
      branch: master
      tags: true
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key: $GH_TOKEN
    file_glob: true
    file: "dist/*"
    on:
      branch: master
      tags: true
