os: linux
language: node_js
node_js:
  - '14'
env:
  - EXTENSION_ID=mmcgnaachjapbbchcpjihhgjhpfcnoan
deploy:
  # Chrome Webstore
  - provider: script
    edge: true
    script: npm run release
    on:
      branch: master
      tags: true
  # GitHub release
  - provider: releases
    edge: true
    overwrite: true
    token: $GH_TOKEN
    file_glob: true
    file: "dist/*"
    on:
      branch: master
      tags: true
