name: Release extension
env:
  EXTENSION_ID: 'mmcgnaachjapbbchcpjihhgjhpfcnoan'
on:
  release:
    types:
      - published

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: npm install
      - name: Run build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

  publish_to_chrome:
    name: Publish to Chrome Web Store
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install packages
        run: npm install
      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: build
          path: build
      - name: Publish
        id: publish-chrome
        run: npm run release:cws
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  publish_to_edge:
    name: Publish to Microsoft Edge Addons
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: wdzeng/edge-addon@v2
        with:
          product-id: cb7fb69e-1443-4100-bdf7-60140851c86d
          zip-path: dist/Open-New-Tab-After-Current-Tab_v${{ steps.get_current_release.outputs.tag_name }}.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          api-key: ${{ secrets.EDGE_API_KEY }}

  publish_to_github:
    name: Publish to GitHub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist
      - name: Add artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true
