name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install packages
      run: npm install

    - name: Run test
      run: npm run test
